/**
 * Levels 1–5: the gentle on-ramp.
 * 1 move + dog · 2 tokens routing · 3 vision cones · 4 hiding · 5 decoys
 */

import type { LevelSpec } from "../types";

export const level01: LevelSpec = {
  id: 1,
  name: "The Couch",
  subtitle: "Everyone's finally asleep. The couch calls.",
  theme: "roseDusk",
  grid: { w: 26, h: 20 },
  rooms: [{ x: 0, z: 0, w: 26, h: 20 }],
  windows: [[7, 0], [8, 0], [13, 0], [0, 13], [0, 14]],
  furniture: [
    { shape: "couch",       x: 19, z: 11, w: 5, h: 2, label: "couch" },
    { shape: "sideTable",   x: 24, z: 11, w: 1, h: 1, label: "sideTable" },
    { shape: "coffeeTable", x: 20, z: 14, w: 3, h: 1 },
    { shape: "lamp",        x: 18, z: 11, w: 1, h: 1 },
    { shape: "armchair",    x: 16, z: 1,  w: 2, h: 2 },
    { shape: "tvUnit",      x: 1,  z: 8,  w: 1, h: 4, rot: 1 },
    { shape: "bookcase",    x: 1,  z: 2,  w: 1, h: 4, rot: 1 },
    { shape: "plant",       x: 1,  z: 18, w: 1, h: 1 },
    { shape: "plant",       x: 24, z: 1,  w: 1, h: 1 },
    { shape: "pictureFrame", x: 11, z: 0, w: 1, h: 1, walkable: true },
  ],
  rugs: [{ x: 17, z: 10, w: 8, h: 6 }],
  start: [2, 2],
  goal: { x: 18, z: 14, label: "The Couch" },
  npcs: [{ type: "dog", x: 12, z: 9 }],
  tokens: [
    { x: 3,  z: 16, type: "coffee" },
    { x: 12, z: 2,  type: "book" },
    { x: 16, z: 17, type: "chocolate" },
  ],
  relax: {
    pose: "sit", prop: "wine", particles: "hearts",
    quote: "Aaah… finally.",
    seat: [21, 12], face: 0, seatHeight: 0.17,
  },
  intro: "That wine isn't going to drink itself…",
  winText: "Silence achieved. Momentarily.",
  caughtLines: ["The tail thump gave you away.", "He heard the floor creak. Of course he did."],
};

export const level02: LevelSpec = {
  id: 2,
  name: "Cold Coffee",
  subtitle: "It has been reheated four times. Never again.",
  theme: "mintDawn",
  grid: { w: 28, h: 22 },
  rooms: [{ x: 0, z: 0, w: 28, h: 22 }],
  windows: [[5, 0], [6, 0], [20, 0], [0, 10], [0, 11]],
  furniture: [
    { shape: "counter",       x: 2,  z: 1,  w: 8, h: 1 },
    { shape: "stove",         x: 10, z: 1,  w: 2, h: 1 },
    { shape: "counter",       x: 12, z: 1,  w: 3, h: 1 },
    { shape: "fridge",        x: 15, z: 1,  w: 2, h: 2 },
    { shape: "cabinet",       x: 22, z: 1,  w: 3, h: 1 },
    { shape: "kitchenIsland", x: 10, z: 8,  w: 7, h: 3, label: "island" },
    { shape: "barStool",      x: 11, z: 12, w: 1, h: 1 },
    { shape: "barStool",      x: 13, z: 12, w: 1, h: 1 },
    { shape: "barStool",      x: 15, z: 12, w: 1, h: 1 },
    { shape: "diningTable",   x: 3,  z: 14, w: 4, h: 3 },
    { shape: "diningChair",   x: 2,  z: 15, w: 1, h: 1, rot: 1 },
    { shape: "diningChair",   x: 8,  z: 15, w: 1, h: 1, rot: 3 },
    { shape: "diningChair",   x: 5,  z: 18, w: 1, h: 1, rot: 2 },
    { shape: "counter",       x: 24, z: 17, w: 2, h: 1, label: "coffeeNook" },
    { shape: "barStool",      x: 24, z: 19, w: 1, h: 1, label: "coffeeStool" },
    { shape: "plant",         x: 26, z: 1,  w: 1, h: 1 },
    { shape: "plant",         x: 1,  z: 20, w: 1, h: 1 },
  ],
  rugs: [{ x: 10, z: 12, w: 7, h: 2 }],
  start: [2, 3],
  goal: { x: 23, z: 18, label: "The Coffee Machine" },
  npcs: [{ type: "dog", x: 7, z: 8 }],
  tokens: [
    { x: 3,  z: 11, type: "coffee" },
    { x: 26, z: 5,  type: "book" },
    { x: 9,  z: 19, type: "chocolate" },
  ],
  relax: {
    pose: "sit", prop: "coffee", particles: "steam",
    quote: "Still hot. STILL HOT.",
    seat: [24, 19], face: -Math.PI / 2, seatHeight: 0.2,
  },
  intro: "One hot coffee. That's all I ask.",
  winText: "The yoga pants were worth every penny.",
  caughtLines: ["He heard the mug. HOW did he hear the mug?"],
};

export const level03: LevelSpec = {
  id: 3,
  name: "The Bubble Bath",
  subtitle: "Bath bombs: activated. Mission: commence.",
  theme: "lagoon",
  grid: { w: 32, h: 24 },
  rooms: [
    { x: 0,  z: 0, w: 21, h: 24 },
    { x: 20, z: 0, w: 12, h: 24 },
  ],
  doors: [[20, 11], [20, 12]],
  windows: [[5, 0], [6, 0], [25, 0], [26, 0], [0, 16], [0, 17]],
  furniture: [
    // bedroom / hallway
    { shape: "bed",     x: 1,  z: 2,  w: 4, h: 6, rot: 1, label: "bed" },
    { shape: "dresser", x: 1,  z: 12, w: 1, h: 4, rot: 1 },
    { shape: "bench",   x: 8,  z: 1,  w: 3, h: 1 },
    { shape: "toybox",  x: 17, z: 19, w: 2, h: 2 },
    { shape: "plant",   x: 1,  z: 21, w: 1, h: 1 },
    { shape: "plant",   x: 18, z: 1,  w: 1, h: 1 },
    // bathroom
    { shape: "bathtub", x: 27, z: 3,  w: 3, h: 6, label: "tub" },
    { shape: "vanity",  x: 21, z: 1,  w: 3, h: 1 },
    { shape: "toilet",  x: 21, z: 6,  w: 1, h: 1, rot: 1 },
    { shape: "laundryBasket", x: 21, z: 20, w: 1, h: 1 },
    { shape: "plant",   x: 30, z: 21, w: 1, h: 1 },
  ],
  rugs: [{ x: 24, z: 11, w: 4, h: 4, round: true }],
  start: [2, 9],
  goal: { x: 25, z: 6, label: "The Bathtub" },
  npcs: [
    { type: "toddler", x: 8, z: 5, patrol: [[8, 5], [16, 5], [16, 18], [8, 18]] },
  ],
  tokens: [
    { x: 4,  z: 20, type: "book" },
    { x: 18, z: 10, type: "coffee" },
    { x: 28, z: 15, type: "chocolate" },
  ],
  relax: {
    pose: "soak", prop: "bath", particles: "bubbles",
    quote: "Pure. Bliss.",
    seat: [28, 6], face: 0, seatHeight: 0.1,
  },
  intro: "Bath bombs: activated. Mission: commence.",
  winText: "Do not perceive me.",
  caughtLines: ["\"MOMMY! Bubbles?! I LOVE BUBBLES!\""],
};

export const level04: LevelSpec = {
  id: 4,
  name: "Hide & Sneak",
  subtitle: "The blanket forts are load-bearing now.",
  theme: "nurseryNoon",
  grid: { w: 30, h: 24 },
  rooms: [{ x: 0, z: 0, w: 30, h: 24 }],
  walls: [[10, 1, 10, 9], [10, 14, 10, 22]],
  windows: [[6, 0], [7, 0], [18, 0], [19, 0]],
  furniture: [
    { shape: "crib",         x: 24, z: 1,  w: 4, h: 3, label: "crib" },
    { shape: "rockingChair", x: 21, z: 4,  w: 2, h: 2 },
    { shape: "toybox",       x: 12, z: 1,  w: 2, h: 2 },
    { shape: "toyBlocks",    x: 15, z: 8,  w: 2, h: 2 },
    { shape: "dresser",      x: 28, z: 8,  w: 1, h: 4, rot: 3 },
    { shape: "beanbag",      x: 26, z: 19, w: 2, h: 2, label: "beanbag" },
    { shape: "bookcase",     x: 12, z: 22, w: 4, h: 1, rot: 2 },
    { shape: "shelf",        x: 1,  z: 1,  w: 1, h: 3, rot: 1 },
    { shape: "plant",        x: 1,  z: 21, w: 1, h: 1 },
  ],
  rugs: [{ x: 14, z: 12, w: 8, h: 6, round: true }],
  start: [3, 3],
  goal: { x: 25, z: 20, label: "The Beanbag" },
  npcs: [
    { type: "toddler", x: 14, z: 12, patrol: [[14, 12], [26, 12]] },
  ],
  tokens: [
    { x: 5,  z: 20, type: "coffee" },
    { x: 18, z: 2,  type: "book" },
    { x: 24, z: 17, type: "chocolate" },
  ],
  hidingSpots: [[13, 5], [20, 16], [13, 18]],
  relax: {
    pose: "lounge", prop: "book", particles: "zzz",
    quote: "Chapter one. Again. Finally.",
    seat: [26, 19], face: Math.PI / 4, seatHeight: 0.12,
  },
  intro: "If I can see her, she can see me.",
  winText: "They'll never know you were here.",
  caughtLines: ["\"MOMMY WHATCHA DOOOOING?\""],
};

export const level05: LevelSpec = {
  id: 5,
  name: "The Decoy",
  subtitle: "Nobody touches MY chocolate.",
  theme: "honeyPlum",
  grid: { w: 32, h: 24 },
  rooms: [{ x: 0, z: 0, w: 32, h: 24 }],
  walls: [[22, 14, 30, 14], [22, 15, 22, 22]],
  doors: [[26, 14], [27, 14]],
  windows: [[5, 0], [6, 0], [15, 0], [0, 16], [0, 17]],
  furniture: [
    { shape: "counter",       x: 2,  z: 1,  w: 7, h: 1 },
    { shape: "stove",         x: 9,  z: 1,  w: 2, h: 1 },
    { shape: "fridge",        x: 12, z: 1,  w: 2, h: 2 },
    { shape: "cabinet",       x: 16, z: 1,  w: 3, h: 1 },
    { shape: "kitchenIsland", x: 6,  z: 6,  w: 5, h: 3 },
    { shape: "diningTable",   x: 4,  z: 16, w: 4, h: 3 },
    { shape: "diningChair",   x: 3,  z: 17, w: 1, h: 1, rot: 1 },
    { shape: "diningChair",   x: 9,  z: 17, w: 1, h: 1, rot: 3 },
    { shape: "sideTable",     x: 1,  z: 12, w: 1, h: 1, label: "keysBowl", hasDecoy: true },
    { shape: "pantryShelf",   x: 24, z: 22, w: 6, h: 1, rot: 2 },
    { shape: "pantryShelf",   x: 30, z: 16, w: 1, h: 4, rot: 3 },
    { shape: "floorCushion",  x: 28, z: 19, w: 1, h: 1, label: "cushion" },
    { shape: "plant",         x: 1,  z: 21, w: 1, h: 1 },
    { shape: "plant",         x: 30, z: 1,  w: 1, h: 1 },
  ],
  rugs: [{ x: 3, z: 15, w: 7, h: 5 }],
  start: [2, 3],
  goal: { x: 26, z: 19, label: "The Chocolate Stash" },
  npcs: [
    { type: "husband", x: 24, z: 10, patrol: [[24, 10], [12, 10]] },
  ],
  tokens: [
    { x: 14, z: 6,  type: "coffee" },
    { x: 2,  z: 8,  type: "book" },
    { x: 29, z: 21, type: "chocolate" },
  ],
  decoyItems: [
    {
      itemName: "Car Keys", itemEmoji: "🔑",
      sourceLabel: "keysBowl", meshColor: "#E8C44E", targetNpc: "husband",
    },
  ],
  relax: {
    pose: "sit", prop: "chocolate", particles: "hearts",
    quote: "Worth every sneaky step.",
    seat: [28, 19], face: -Math.PI / 2, seatHeight: 0.1,
  },
  intro: "Nobody touches MY chocolate.",
  winText: "Emergency rations: secured.",
  caughtLines: ["\"Oh hey babe, have you seen my keys?\""],
};
